# Job from R2Devops hub --> r2devops.io

stages:
  - build

mkdocs:
  image:
    name: squidfunk/mkdocs-material:${IMAGE_TAG}
    entrypoint: [""]
  stage: build
  variables:
    MKDOCS_OUTPUT_PATH: 'website_build/'
    MKDOCS_ADDITIONAL_PLUGINS: 'mkdocs-awesome-pages-plugin;mkdocs-git-revision-date-localized-plugin;mkdocs-macros-plugin;mkdocs-same-dir'

    IMAGE_TAG: "9.5.2"
  script:
    - |
      if [[ ${MKDOCS_ADDITIONAL_PLUGINS} != "" ]]; then
    # Save default IFS
    - oldIFS=$IFS
    # Modifying IFS
    - export IFS=";"
    - for plugin in $MKDOCS_ADDITIONAL_PLUGINS; do
        # Restore to default IFS
    -   IFS=$oldIFS
        # Run the script
    -   pip3 install $plugin
        # Modifying IFS for the next loop
    -   export IFS=";"
    - done
      fi
    - mkdocs build -d "$MKDOCS_OUTPUT_PATH"
  artifacts:
    when: always
    expose_as: "Mkdocs build"
    paths:
      - "$MKDOCS_OUTPUT_PATH"
      # Below path is a workaround to provide artifact exposition in MR if
      # default output value is used. See https://r2devops.io/_/r2devops-bot/mkdocs/
      - "website_build/"
