# Job from R2Devops hub --> r2devops.io


stages:
  - tests


yarn_test:
  stage: tests
  image:
    name: node:${IMAGE_TAG}
    entrypoint: [""]
  variables:
    PROJECT_ROOT: "."
    YARN_INSTALL_OPTIONS: ""
    YARN_TEST_OPTIONS: ""
    IMAGE_TAG: "20-buster"
  script:
    # Working directory
    - cd $PROJECT_ROOT
    # Run yarn install
    - yarn install $YARN_INSTALL_OPTIONS
    # Run yarn test
    - yarn test $YARN_TEST_OPTIONS
