stages:
  - tests

php_security_checker:
  image: 
    name: alpine:${IMAGE_TAG}
    entrypoint: [""]
  stage: tests
  variables:
    COMPOSER_PATH: "./composer.lock"
    FORMAT_OUTPUT: ""
    SECURITY_CHECKER_VERSION: "2.0.6"
    IMAGE_TAG: "3.17"
  script:
    - wget -O ./local-php-security-checker "https://github.com/fabpot/local-php-security-checker/releases/download/v${SECURITY_CHECKER_VERSION}/local-php-security-checker_${SECURITY_CHECKER_VERSION}_linux_amd64"
    - chmod +x ./local-php-security-checker
    - ./local-php-security-checker  --path="${CI_PROJECT_DIR}/${COMPOSER_PATH}" $FORMAT_OUTPUT