# Job from R2Devops hub --> r2devops.io

stages:
  - tests

golint:
  image: golang:${IMAGE_TAG}
  stage: tests
  variables:
    PROJECT_ROOT: "."
    GOLINT_CONFIG: ""
    GOLINT_REPORTS_DIRECTORY: "reports"
    GOLINT_OUTPUT_FORMAT: "junit-xml" 
    ADDITIONAL_OPTIONS: ""
    GOLINT_VERSION: "1.51.2"
    IMAGE_TAG: "alpine3.17"
  script:
    - wget -O ./golint.tar.gz "https://github.com/golangci/golangci-lint/releases/download/v${GOLINT_VERSION}/golangci-lint-${GOLINT_VERSION}-linux-amd64.tar.gz"
    - tar -xzf ./golint.tar.gz
    - mv ./golangci-lint-${GOLINT_VERSION}-linux-amd64/golangci-lint /usr/local/bin/golangci-lint
    - cd ${CI_PROJECT_DIR}/${PROJECT_ROOT}
    - mkdir ${GOLINT_REPORTS_DIRECTORY}
    - touch ${GOLINT_REPORTS_DIRECTORY}/report-golint.xml
    - touch ${GOLINT_REPORTS_DIRECTORY}/report-golint.json
    - REPORTS_FILES="${GOLINT_REPORTS_DIRECTORY}-files"
    - mkdir ${REPORTS_FILES}
    - CONFIG_OPTIONS=""
    - $([ "${GOLINT_CONFIG}" != "" ]) && CONFIG_OPTIONS="--config ${GOLINT_CONFIG}"
    - FORMAT_OPTIONS=""
    - if [ "${GOLINT_OUTPUT_FORMAT}" != "colored-line-number" ]; then
    -   FORMAT_OPTIONS="--out-format ${GOLINT_OUTPUT_FORMAT}"
    - fi
    - EXTENSION_REPORT=""
    - if [ "${GOLINT_OUTPUT_FORMAT}" == "junit-xml" ]; then
    -   EXTENSION_REPORT="xml"
    - fi
    - if [ "${GOLINT_OUTPUT_FORMAT}" == "code-climate" ]; then
    -   EXTENSION_REPORT="json"
    - fi
    - if [ ! -z "${EXTENSION_REPORT}" ]; then
    -   if ! golangci-lint run -v ${ADDITIONAL_OPTIONS} ${CONFIG_OPTIONS} ${FORMAT_OPTIONS} > ${REPORTS_FILES}/report-golint.${EXTENSION_REPORT}; then
    -     cp ${REPORTS_FILES}/* ${CI_PROJECT_DIR}/${PROJECT_ROOT}/${GOLINT_REPORTS_DIRECTORY}
    -     exit 1
    -   fi
    - else
    -   golangci-lint run -v ${ADDITIONAL_OPTIONS} ${CONFIG_OPTIONS} ${FORMAT_OPTIONS}
    - fi


  artifacts:
    when: always
    paths:
    - ${CI_PROJECT_DIR}/${PROJECT_ROOT}/${GOLINT_REPORTS_DIRECTORY}
    reports:
      junit: ${CI_PROJECT_DIR}/${PROJECT_ROOT}/${GOLINT_REPORTS_DIRECTORY}/report-golint.xml
      codequality: ${CI_PROJECT_DIR}/${PROJECT_ROOT}/${GOLINT_REPORTS_DIRECTORY}/report-golint.json