# Job from R2Devops hub --> r2devops.io


stages:
  - tests


npm_test:
  stage: tests
  image:
    name: node:${IMAGE_TAG}
    entrypoint: [""]
  variables:
    PROJECT_ROOT: "."
    NPM_INSTALL_OPTIONS: ""
    NPM_TEST_OPTIONS: ""
    IMAGE_TAG: "20-buster"
  script:
    # Working directory
    - cd $PROJECT_ROOT
    # Run npm install
    - npm install $NPM_INSTALL_OPTIONS
    # Run npm test
    - npm test $NPM_TEST_OPTIONS
